### ISSUE TITLE
s2i with ruby 2.6 does not create secret_key_base

### ISSUE THREAD

**Issue by pvalena** [sclorg/rails-ex#146]
Basically, from what I've gathered:
```
s2i build https://github.com/sclorg/rails-ex registry.access.redhat.com/ubi8/ruby-26 rails-ex:2.6
/tmp/src ~
---> Building your Ruby application from source ...
You are replacing the current global value of set, which is currently "--local deployment true"
---> Running 'bundle install --retry 2' ...
You are replacing the current global value of set, which is currently "--local without development:test"
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/..........
Fetching rake 13.0.3
Errno::EACCES: Permission denied @ rb_file_s_rename -
```
Here, `rename` fails ^^^ ; do I understand correctly that there's installation destination missing? (and the $HOME one is wrong) 

```
(/opt/app-root/src/.gem/ruby/cache/rake-13.0.3.gem,
/usr/share/gems/cache/rake-13.0.3.gem)
An error occurred while installing rake (13.0.3), and Bundler cannot continue.
Make sure that `gem install rake -v '13.0.3' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
coffee-rails was resolved to 5.0.0, which depends on
railties was resolved to 6.1.3.1, which depends on
rake
---> Cleaning up unused ruby gems ...
Running `bundle clean --verbose` with bundler 1.17.2
Cleaning all the gems on your system is dangerous! If you're sure you want to
remove every system gem not in this bundle, run `bundle clean --force`.
---> No master key present in environment, generating ...
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find rake-13.0.3 in any of the sources (Bundler::GemNotFound)
        from /usr/share/gems/gems/bundler-1.17.2/lib/bundler/spec_set.rb:85:in `map!'
        from /usr/share/gems/gems/bundler-1.17.2/lib/bundler/spec_set.rb:85:in `materialize'
        from /usr/share/gems/gems/bundler-1.17.2/lib/bundler/definition.rb:170:in `specs'
        from /usr/share/gems/gems/bundler-1.17.2/lib/bundler/definition.rb:237:in `specs_for'
        from /usr/share/gems/gems/bundler-1.17.2/lib/bundler/definition.rb:226:in `requested_specs'
        from /usr/share/gems/gems/bundler-1.17.2/lib/bundler/runtime.rb:108:in `block in definition_method'
        from /usr/share/gems/gems/bundler-1.17.2/lib/bundler/runtime.rb:20:in `setup'
        from /usr/share/gems/gems/bundler-1.17.2/lib/bundler.rb:107:in `setup'
        from /usr/share/gems/gems/bundler-1.17.2/lib/bundler/setup.rb:20:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /tmp/src/config/boot.rb:3:in `<top (required)>'
        from bin/rails:4:in `require_relative'
        from bin/rails:4:in `<main>'
~

```

This should have probably failed earlier, with the bundle install; which failed because it tried to install to some invalid destination, probably.

@jackorp PTAL.

Full log: https://gist.github.com/b61bcc35accdcb1807c10d3fe9c323e9

_ _ _ _ 

@yselkowitz  FYI:  It's probably just environment issue.

**Comment by jackorp** [comment]
Hmm, the script I took from s2i-ruby uses `bundle config set --local path './bundle'` before installing, I wonder if that option is even taken into account properly by bundler v1.17.2...

**Comment by jackorp** [comment]
hmm, lines 4 and 6 from [the log](https://gist.github.com/b61bcc35accdcb1807c10d3fe9c323e9) look suspicious. Looks like some global value is being overwritten?

**Comment by jackorp** [comment]
The issue is that the old bundler apparently has different CLI usage of `bundle config`, it interprets `set` verb as a key under which it saves the value. Luckily it looks like newer bundler supports the older syntax as well so the `bundle config set` can be just `bundle config`.
